# fly.toml - TailorBlend AI Consultant Frontend UI
# Deployment configuration for fly.io

app = "tailorblend-frontend-ui"
primary_region = "jnb"  # Johannesburg, South Africa

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://0.0.0.0:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  # HTTP options for proxying SSE streams from backend
  [http_service.http_options]
    response.read_timeout = "5m"  # Allow long-running requests to backend
    h2_backend = false  # Force HTTP/1.1 for compatibility

  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  # Health check with increased tolerances
  [[http_service.checks]]
    grace_period = "180s"  # Increased from 60s for Blazor Server startup
    interval = "30s"
    method = "GET"
    timeout = "10s"  # Increased from 5s for more tolerance
    path = "/health"

# VM configuration - Optimized for cost (cheapest always-on option)
# shared-cpu-1x with 256MB = $2.02/month (was $3.32 with 512MB)
# Blazor Server is lightweight enough for 256MB with swap
# If you experience OOM errors, upgrade to 512MB
[vm]
  size = "shared-cpu-1x"
  memory = "256mb"

# Swap provides emergency buffer if 256MB RAM is insufficient
# This prevents crashes during memory spikes
swap_size_mb = 512

# Environment variables for production
# PythonApi__BaseUrl should be set via fly secrets:
#   fly secrets set PythonApi__BaseUrl="https://tailorblend-backend-api.fly.dev"
