# fly.toml - TailorBlend AI Consultant Blazor Frontend
# Deployment configuration for fly.io with SignalR support

app = "tailorblend-frontend-ui"
primary_region = "jnb"  # Johannesburg, South Africa

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://+:8080"
  # Backend API URL (for server-side calls)
  PythonApi__BaseUrl = "https://tailorblend-backend-api.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Allow full shutdown when idle for cost savings

  # HTTP options for SignalR + SSE streaming support
  [http_service.http_options]
    response.read_timeout = "10m"  # Long timeout for SignalR circuits + SSE streams
    h2_backend = false  # Force HTTP/1.1 for SignalR compatibility

  # Concurrency settings optimized for SignalR
  [http_service.concurrency]
    type = "connections"
    hard_limit = 100  # Lower limit for SignalR persistent connections
    soft_limit = 75

  # Health check configuration
  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"  # Blazor root page

# VM configuration - Optimized for cost
# shared-cpu-1x with 512MB for Blazor Server (needs more RAM than API)
[vm]
  size = "shared-cpu-1x"
  memory = "512mb"

# Swap provides buffer for SignalR memory spikes
swap_size_mb = 256
