name: Deploy to Fly.io

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy TailorBlend Frontend
    runs-on: ubuntu-latest

    # Ensure only one deployment runs at a time
    concurrency: deploy-group

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
